<a href="https://colab.research.google.com/github/Nishanta04/Mathematics-for-AI/blob/main/Cosine_Similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Cosine Similarity Analysis

Cosine similarity measures the cosine of the angle between two non-zero vectors. It is often used to measure similarity between documents or text, where the magnitude of the vectors doesn't matter as much as their orientation.

*   **Cosine Similarity**: Values range from -1 (opposite) to 1 (identical). 0 indicates orthogonality.
*   **Cosine Distance**: Calculated as `1 - Cosine Similarity`.

In [4]:
import numpy as np
import pandas as pd

In [6]:
# Custom Cosine Similarity
def cosine_similarity_manual(v1, v2):
    dot_product = np.dot(v1, v2)
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)
    if norm_v1 == 0 or norm_v2 == 0:
        return 0.0  # Handle zero vectors
    return dot_product / (norm_v1 * norm_v2)

# Custom Cosine Distance
def cosine_distance_manual(v1, v2):
    return 1 - cosine_similarity_manual(v1, v2)

# Sample data for Cosine Similarity (e.g., word count vectors or embeddings)
cos_data = np.array([
    [1, 1, 0, 1, 0, 1], # Document 1
    [1, 1, 1, 0, 1, 0], # Document 2
    [0, 1, 0, 1, 0, 1], # Document 3
    [0, 0, 0, 1, 0, 0]  # Document 4
])
df_cos = pd.DataFrame(cos_data, columns=[f'Term_{i+1}' for i in range(cos_data.shape[1])])
display(df_cos)

num_samples = len(cos_data)

print('\n--- Cosine Similarity Matrix ---')
cos_sim_mat = pd.DataFrame(0.0, index=df_cos.index, columns=df_cos.index)
for i in range(num_samples):
    for j in range(num_samples):
        if i == j:
            cos_sim_mat.loc[i, j] = 1.0 # Similarity with itself is 1
            continue
        cos_sim_mat.loc[i, j] = cosine_similarity_manual(cos_data[i], cos_data[j])
display(cos_sim_mat)

print('\n--- Cosine Distance Matrix (1 - Cosine Similarity) ---')
cos_dist_mat = pd.DataFrame(0.0, index=df_cos.index, columns=df_cos.index)
for i in range(num_samples):
    for j in range(num_samples):
        if i == j:
            continue
        cos_dist_mat.loc[i, j] = cosine_distance_manual(cos_data[i], cos_data[j])
display(cos_dist_mat)

   Term_1  Term_2  Term_3  Term_4  Term_5  Term_6
0       1       1       0       1       0       1
1       1       1       1       0       1       0
2       0       1       0       1       0       1
3       0       0       0       1       0       0

--- Cosine Similarity Matrix ---

          0         1         2        3
0  1.000000  0.500000  0.866025  0.50000
1  0.500000  1.000000  0.288675  0.00000
2  0.866025  0.288675  1.000000  0.57735
3  0.500000  0.000000  0.577350  1.00000

--- Cosine Distance Matrix (1 - Cosine Similarity) ---

          0         1         2        3
0  0.000000  0.500000  0.133975  0.50000
1  0.500000  0.000000  0.711325  1.00000
2  0.133975  0.711325  0.000000  0.42265
3  0.500000  1.000000  0.422650  0.00000